#!/usr/bin/env python
"""One-shot: push the fine-tuned FinBERT (src/train_sentiment.py's output,
models/finbert-financial-news/) to the Hugging Face Hub as
gamug/FinBERT-financial-news, with a model card documenting the training
data, procedure, and measured metrics.

Requires HF_TOKEN in the environment/.env (write scope). Run once, after
src/train_sentiment.py and after the real-data pipeline-integration
comparison (docs/evaluation.md's 2026-09-13 fine-tuning follow-up) --
the model card embeds those numbers, so this should be the last step.

Usage:
    uv run python scripts/publish_finbert_financial_news_2026_09_13.py
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from dotenv import load_dotenv
from huggingface_hub import HfApi

load_dotenv()

MODEL_DIR = Path("models/finbert-financial-news")
METRICS_PATH = Path("data/sentiment_finetune/test_metrics.json")
REPO_ID = "gamug/FinBERT-financial-news"

MODEL_CARD = """---
license: cc-by-nc-4.0
base_model: ProsusAI/finbert
language:
- en
pipeline_tag: text-classification
tags:
- finance
- financial
- sentiment
- sentiment-analysis
- bert
- finbert
metrics:
- accuracy
- f1
- precision
- recall
---

# FinBERT-financial-news

A continued fine-tune of [`ProsusAI/finbert`](https://huggingface.co/ProsusAI/finbert) on
**5,000 sentences from real English-language financial news articles (2010s-2020s), labeled
by an LLM (DeepSeek `deepseek-chat`)** from an investor/price-impact perspective — not a
from-scratch retrain: the label space (`positive`/`negative`/`neutral`) and task framing are
unchanged from the base model, only the training sentences are new.

## Why this exists

`ProsusAI/finbert` was fine-tuned on [Financial PhraseBank](https://huggingface.co/datasets/takala/financial_phrasebank)
— ~4,840 sentences from **2014 English-language news about OMX Helsinki (Nordic) listed
companies**, via LexisNexis. That's a real, measurable domain/vocabulary gap for a pipeline
scoring 2010s-2020s English-language financial news on globally-listed companies: real
disagreement cases found during evaluation included the base model missing "crushed" as a
positive idiom ("Amazon and Alphabet crushed earnings"), and terms/instruments (e.g.
cryptocurrency) that didn't meaningfully exist in the base model's training window.
This model targets that specific gap — a vocabulary/domain refresh, not an architecture or
label-space change.

## Training data

- **Source sentences**: split from the `body_text` of real financial-news articles already
  sampled across this project's own LLM-as-judge sentiment evaluation runs (a pool naturally
  covering positive/negative/neutral content via that harness's stratified sampling design,
  not a fresh uniform draw).
- **Labels**: generated by `deepseek-chat` (temperature 0), one sentence at a time, in
  isolation, with the same investor/price-impact framing Financial PhraseBank's own human
  annotators used ("does this sentence read as good news, bad news, or neither for the
  company/asset it concerns, from the perspective of a long-only equity investor").
- **Size**: 5,000 sentences, 100% labeling success rate. Class distribution: 938 positive
  (18.8%), 893 negative (17.9%), 3,169 neutral (63.4%) — real financial-news sentences skew
  neutral/factual, consistent with prior findings on this same corpus.
- **Split**: 80/10/10 train/validation/test, stratified per label (4,004 / 498 / 498).

**Important limitation**: these labels are LLM-generated (silver-standard), not
human-annotated ground truth. They were not independently verified against a human-labeled
reference set. Treat the test-set metrics below as "agreement with this specific LLM's
sentence-level judgment," not an absolute accuracy figure — the same caveat this project
applies to every LLM-as-judge number in its own evaluation docs.

## Training procedure

Continued fine-tuning from the `ProsusAI/finbert` checkpoint (not vanilla BERT) via
Hugging Face `Trainer`:

- learning rate: 2e-5
- batch size: 16 (train) / 32 (eval)
- epochs: 4
- weight decay: 0.01
- mixed precision (fp16)
- `load_best_model_at_end=True`, selected by validation macro F1
- seed: 42

## Evaluation results

### Held-out sentence-level test set (n=498, LLM-labeled — see limitation above)

| metric | value |
|---|---|
| Accuracy | 0.813 |
| Macro F1 | 0.774 |
| F1 — positive | 0.798 |
| F1 — negative | 0.667 |
| F1 — neutral | 0.858 |
| Precision — positive | 0.789 |
| Precision — negative | 0.682 |
| Precision — neutral | 0.855 |
| Recall — positive | 0.806 |
| Recall — negative | 0.652 |
| Recall — neutral | 0.861 |

### Downstream pipeline evaluation (real financial news, LLM-judge, article-level)

This model was also evaluated in the actual production pipeline it was built for —
[`portfolio-nlp`](https://github.com/gamug/portfolio-nlp) — substituted into an
entity-scoped, chunk-level aggregation scheme (score each ~510-token chunk, weight chunks
naming the article's own subject company/ticker over everything else), on the same
2,000-article real-news sample and LLM-judge harness used to validate every other candidate
design for this pipeline's sentiment stage:

| metric | base FinBERT (same aggregation) | **this model (same aggregation)** |
|---|---|---|
| `recall_negative` (this pipeline's priority metric) | 0.856 | 0.812 |
| **`precision_negative`** | 0.376 | **0.505** |
| `f1_negative` | 0.523 | 0.623 |
| `macro_f1_vs_judge` | 0.625 | **0.737** |
| `agreement_rate` | 0.585 | **0.697** |
| `recall_positive` | 0.520 | **0.790** |
| `precision_neutral` | 0.871 | 0.935 |

`recall_negative` dips slightly (still well inside this pipeline's documented healthy range)
but every other headline metric improves substantially — most notably `precision_negative`
(+13 points), the single most persistent weak point across every design this project
evaluated for this stage. Net read: a real, broad-based improvement, not a narrow win on one
metric traded against a loss everywhere else.

See `docs/evaluation.md`'s 2026-09-13 fine-tuning follow-up in the repo above for the full
comparison, methodology, and caveats (the LLM-judge is itself a model, not ground truth; the
judge and this model's training labels both ultimately trace to the same LLM provider, a
methodological limitation disclosed there in full, not glossed over here).

## Usage

```python
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

tokenizer = AutoTokenizer.from_pretrained("gamug/FinBERT-financial-news")
model = AutoModelForSequenceClassification.from_pretrained("gamug/FinBERT-financial-news")

classifier = pipeline("text-classification", model=model, tokenizer=tokenizer)
classifier("Acme Corp reported record profit and raised its full-year guidance.")
```

Recommended pre/post-processing: same as the base model — chunk long documents rather than
truncating (this checkpoint keeps BERT-base's 512-token limit), and if aggregating multiple
chunks/sentences per document yourself, consider scoping/weighting toward the actual subject
of the document rather than a plain average (see the `portfolio-nlp` repo above for one
worked design and its measured trade-offs).

## License

Derivative of two upstream works with different licenses:

- Base model `ProsusAI/finbert`: itself derivative of `nlpaueb/sec-bert-base`-adjacent work
  and Financial PhraseBank (`CC-BY-NC-4.0`).
- Training data here: LLM-generated from real news article text; the underlying articles are
  not redistributed, only derived per-sentence sentiment labels used for training.

Released under **`CC-BY-NC-4.0`**, matching the base model's own license: attribution
required, **non-commercial use only**.
"""


def main() -> None:
    token = os.environ["HF_TOKEN"]
    api = HfApi(token=token)

    print(f"Creating/confirming repo {REPO_ID} ...")
    api.create_repo(repo_id=REPO_ID, repo_type="model", exist_ok=True)

    print(f"Uploading model files from {MODEL_DIR} ...")
    # allow_patterns alone still matches files *inside* checkpoint-*/ subdirs
    # (Trainer's intermediate saves) -- ignore_patterns excludes those
    # directories outright regardless of which files match the allow-list.
    api.upload_folder(
        repo_id=REPO_ID,
        repo_type="model",
        folder_path=str(MODEL_DIR),
        allow_patterns=["*.json", "*.safetensors", "*.txt", "vocab.txt"],
        ignore_patterns=["checkpoint-*/**", "checkpoint-*"],
    )

    card_path = MODEL_DIR / "README.md"
    card_path.write_text(MODEL_CARD)
    print("Uploading model card ...")
    commit_info = api.upload_file(
        path_or_fileobj=str(card_path),
        path_in_repo="README.md",
        repo_id=REPO_ID,
        repo_type="model",
        commit_message="Add model card with training data, procedure, and evaluation metrics",
    )
    print("commit url:", commit_info.commit_url)

    if METRICS_PATH.exists():
        print("Local test metrics on file:", json.loads(METRICS_PATH.read_text())["test_metrics"])


if __name__ == "__main__":
    main()
